# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

WORKDIR /app

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml .
COPY src ./src
COPY scripts ./scripts

# Install the MCP server
RUN pip install --no-cache-dir .

# Default entrypoint
ENTRYPOINT ["reddit-mcp"]
